<?php

namespace Api\Version1Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function getNextAuthors($iStart, $iCount) {
        return $this->getEntityManager('mikado')
            ->createQuery('SELECT a FROM ApiVersion1Bundle:Author a ORDER BY a.id ASC')
            ->setFirstResult( $iStart )
            ->setMaxResults($iCount)
            ->getResult();
    }
}
