app_main:
    resource: "@AppMainBundle/Resources/config/routing.yml"
    prefix:   /

api_version1:
    resource: "@ApiVersion1Bundle/Resources/config/routing.yml"
    prefix:   /api/v1/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
