services:
    app.tokens.action_listener:
        class: Api\Version1Bundle\EventListener\TokenListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }